name: magscot_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - r-base 
  - r-optparse
  - r-dplyr 
  - r-readr 
  - r-funr 
  - r-digest
  - hmmer 
  - prodigal 
  - parallel
  - gawk